# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ideístas
email: hello@guillem.mobi
description: El podcast
baseurl: "/ideistas" # the subpath of your site, e.g. /blog
url: "http://guillemf.github.io" # the base hostname & protocol for your site
twitter_username: guillemf
github_username:  guillemf

# Build settings
markdown: kramdown
